### ISSUE TITLE
@types packages should be dependencies instead of devDependencies

### ISSUE THREAD

**Issue by michaelsbradleyjr** [open-rpc/generator#363]
See: https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html

> Our package exposes declarations from each of those, so any user of our browserify-typescript-extension package needs to have these dependencies as well. For that reason, we used "dependencies" and not "devDependencies", because otherwise our consumers would have needed to manually install those packages. If we had just written a command line application and not expected our package to be used as a library, we might have used devDependencies.

Related to #275.  I ran into this myself yesterday, had to manually install the `@types` packages in order for my TypeScript project that has `@etclabscore/ethereum-json-rpc` as a dependency to build correctly.

Specifically, it seems the `@types` packages in the following file should be moved from devDependencies to dependencies:

https://github.com/open-rpc/generator/blob/master/templates/client/typescript/_package.json

**Comment by BelfordZ** [comment]
Hey @michaelsbradleyjr Thanks for making this issue.

[Ive made a PR for you to review.](https://github.com/open-rpc/generator/pull/364)

It makes me a little sad that types need to be a non-dev dep, but in this case usability is more important than semantic correctness.

Thanks again.

**Comment by michaelsbradleyjr** [comment]
Thanks for addressing the issue so quickly!
