### ISSUE TITLE
Generator imports types with `I` prefix

### ISSUE THREAD

**Issue by bakon11** [open-rpc/generator#414]
**Describe the bug**
When using the generator to create a new typescript server and running open-rpc-generator generate -c ./open-rpc-generator-config.json the types deceleration get prefixed with `I` but it's looking for the name with out `I` and needs to be manually change every time.

**To Reproduce**
Just run `open-rpc-generator generate -c ./open-rpc-generator-config.json` to create a new server

**Expected behavior**
Either remove the `I` from being generated or correct the dependency and add `I`.

**Screenshots**
![image](https://user-images.githubusercontent.com/50184793/80015043-ca2b0800-8496-11ea-8b9d-e267d2347315.png)

![image](https://user-images.githubusercontent.com/50184793/80015071-d616ca00-8496-11ea-8b4e-a077c128f2a2.png)

**Comment by BelfordZ** [comment]
thanks for the issue. On it!
