### ISSUE TITLE
Reduce bundle size for client

### ISSUE THREAD

**Issue by ChillyBwoy** [open-rpc/generator#424]
First of all, thank you for this amazing project. My team decided to use open-rpc as an API to create a new project, but I found that when used in browser, the bundle size is quite large, so i did some research and made some improvements for [@open-rpc/generator](https://github.com/open-rpc/generator) and [@open-rpc/schema-utils-js](https://github.com/open-rpc/schema-utils-js).  It might be better to make the method validation process optional, or even delegate it to the user.

Here are some statistics:

test file:

```js
import client from './client/typescript/build';
```

built with [Parcel](https://github.com/parcel-bundler/parcel):

```sh
$ yarn parcel build index.js
```

```sh
$ ls -lh dist

total 4288
-rw-r--r--  1 chillybwoy  staff   399K May  1 14:07 index.js
-rw-r--r--  1 chillybwoy  staff   1.7M May  1 14:07 index.js.map

$ yarn size-limit

Package size limit has exceeded by 87.19 KB
Size limit: 50 KB
Size:       137.19 KB with all dependencies, minified and gzipped
```

without `MethodCallValidator` (just comment all the lines related to MethodCallValidator in generated client)

```sh
$ ls -lh dist

total 2032
-rw-r--r--  1 chillybwoy  staff   129K May  1 14:09 index.js
-rw-r--r--  1 chillybwoy  staff   823K May  1 14:09 index.js.map

$ yarn size-limit

Size limit: 50 KB
Size:       32.17 KB with all dependencies, minified and gzipped
```

without `MethodCallValidator` and with some `lodash` optimizations from [here](https://github.com/ChillyBwoy/schema-utils-js/commit/52e8aac53be75edf4ff90c70df570734454f3098) and [here](https://github.com/ChillyBwoy/generator/commit/2dea2120eee30b9960fdb0ba9172cf702f88f07f)

```sh
$ ls -lh dist

total 352
-rw-r--r--  1 chillybwoy  staff    43K May  1 14:18 index.js
-rw-r--r--  1 chillybwoy  staff   128K May  1 14:18 index.js.map

$ yarn size-limit

Size limit: 50 KB
Size:       9 KB  with all dependencies, minified and gzipped
```

**Comment by BelfordZ** [comment]
Hey @ChillyBwoy ! Welcome and thank you for opening this issue! 

The idea of optional validation is a good one by me -- feel free to open separate issue to track that feature, or I can do it for you if you would like. I think its a useful option, irrespective of bundle size improvements.

size of the generated package is one of the tech-debt tradeoffs we were ok with making early on, but I agree that its probably time to revisit this problem and make some improvements. I really appreciate the preliminary investigation into MethodCallValidator.

There are a number of tools that I've been working on for dealing with JSON schema, with the idea of swapping out the currently used json schema tools. This should help with the dep size substantially. That said, if you have any quick fix's that we can apply in the meantime that will have minimal impact to functionality, all of us are happy to merge such upgrades.

**Comment by ChillyBwoy** [comment]
The first and simplest approach is to specify this rule in the configuration file and ask the user about it during the initial dialog. This will only change the client library template. Maybe it's a good idea to show a warn about it, e.g. "_If you are going to use method call verification, this may cause the bundle size to increase_".

The second approach is to use dependency injection and pass an instance of the validator to the client constructor, but I'm not sure this will work because it might cause some breaking changes. Also it will require some additional steps from the end user
