### ISSUE TITLE
Add golang client, server and dart client support

### ISSUE THREAD

**Issue by vetcher** [open-rpc/generator#594]
I'm in search for service schema definitions and considering to choose your ecosystem openrpc. My stack is golang backend with microservices (so go <-> go interaction important too) and flutter mobile apps. Right now this tool supports only ts and rust as I can see.

Could you help me understand:
1. How can I help you add go client, go server and dart client templates? I'm already have all generators based on https://github.com/semrush/zenrpc and SMD schema, but I dont know ts nor js at all.
2. Why I need to install node.js and keep it as a dependency for my project? 
I propose to create separate repos for each language, like it does in OpenAPI (aka swagger) or Graphql ecosystems and write generator for each on their own languages. So it would be easier for me to help add more languages.
OR allow to feed templates to your tool on fly (at execution time), protoc and protoc-gen-* (grpc-ecosystem) service generators works exactly like that (https://github.com/grpc-ecosystem/grpc-gateway) and distribute core generator in binary form.

**Comment by shanejonas** [comment]
@vetcher  if you are using golang there is this library to generate the openrpc document from your code: https://github.com/etclabscore/go-openrpc-reflect

Also the advanced section of the webinar is all about `go-openrpc-reflect` and generating documents from code: https://open-rpc.org/webinar/

**Comment by BelfordZ** [comment]
@vetcher Work has been started to get golang clients done. We have the generated typings already, we just need to chose a client and get the template together. If there is someone wanting to put up funding to get that done, it will happen a lot faster :).

**Comment by siemendev** [comment]
@BelfordZ any chance you can publish your current progress so others can join in finishing the golang generation? We're using OpenRPC in our project and want to add golang clients so I would love to bring this to the finish line :)
